### ISSUE TITLE
Repository transfer to HaxeFoundation

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe-markdown#32]
Hey David,

hope you're doing well. Would you mind transferring this repository over to the HaxeFoundation org on GitHub so we can continue to maintain it?

We would also like to add the HaxeFoundation haxelib account to the list of contributors for both this repository and dox. Since it's probably a bit of a hassle for you to set that up, we can handle this ourselves but would like to ask for your permission because we don't like hacking haxelib content without the author's consent.

Thanks!

**Comment by dpeek** [comment]
Hack away! Will transfer now.

**Comment by dpeek** [comment]
Spoke too soon. I need permission to create repositories on HaxeFoundation in order to transfer or something? Or can I add you as a collaborator maybe...

**Comment by Simn** [comment]
Nice, thanks! I've sent you an invite to the org, is that sufficient?

**Comment by Simn** [comment]
Collaborator isn't enough, I don't have access to the settings.

**Comment by dpeek** [comment]
Apparently org member isn't enough either :( Guess I need specific "create repo" permission?

**Comment by Simn** [comment]
I've made you owner of the HaxeFoundation, congrats on your steep career!

**Comment by dpeek** [comment]
Transferred and renamed Haxe back to haXe while I was at it. 🔥

**Comment by Simn** [comment]
Thanks a lot!

**Comment by Gama11** [comment]
I'm guessing you mean the other way around? :D
